from http.server import SimpleHTTPRequestHandler
import socket, os, socketserver
from pyautogui import hotkey
from base64 import b64decode

PORT = 80

def ip_address_helper():
    try:
        host_name = socket.gethostname()
        host_ip = socket.gethostbyname(host_name)
        return host_ip
    except:
        return "IP Error!"

class MyRequestHandler(SimpleHTTPRequestHandler):

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length).decode('utf-8')

        keys = [key.split('=')[1] for key in post_data.split('&')]

        if self.path == '/index.html':
            print(f"Sending keys: {'+'.join(str(k) for k in keys)}...", end=' ')
            hotkey(*keys)
            print("Done!")

        self.do_GET()

    def do_GET(self):
        for local_path in ['/', '/index.html', '/favicon.ico', '/ZoomRemoteDir']:
            if self.path == local_path:
                self.send_local(self.path)
                return
        super().do_GET()


    def send_local(self, path):
        if path == '/favicon.ico':
            if os.path.exists('favicon.ico'):
                super().do_GET()
            else:
                self.decoded_icon = b64decode(favicon)
                self.send_simple_response(self.decoded_icon, 'image/x-icon')

        elif path == '/ZoomRemoteDir':
            f = self.list_directory(os.path.dirname(os.path.realpath(__file__)))
            if f:
                try:
                    self.copyfile(f, self.wfile)
                finally:
                    f.close()

        else:
            if os.path.exists('index.html'):
                super().do_GET()
            else:
                self.encoded_html = index_html.encode('utf-8')
                self.send_simple_response(self.encoded_html, 'text/html')


    def send_simple_response(self, content, ctype):
        self.send_response(200)
        self.send_header("Content-type", ctype)
        self.send_header("Content-Length", len(content))
        self.end_headers()
        self.wfile.write(content)


def main():
    print(f"Starting HTTP server on {ip_address_helper()}:{PORT}...", end=' ')

    with socketserver.TCPServer(("", PORT), MyRequestHandler) as httpd:
        print("Done!")
        httpd.serve_forever()

index_html = """
<html>
<head>
<meta charset="UTF-8">
<title>ZoomRemote</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body { padding: 1rem; }

.button {
  background-color: dodgerblue;
  color: white;
  padding: 1rem;
  height: 10rem;
  font-size:2.5rem;
  white-space:normal;
  border-radius:1rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  display: grid;
  grid-gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
}
</style>
</head>
<body>
<div class="container">
<form action="/index.html" method="post">
<input type="hidden" id="toggle_hand_key_1" name="toggle_hand_key_1" value="alt">
<input type="hidden" id="toggle_hand_key_2" name="toggle_hand_key_2" value="y">
<input type="submit" value="&#x270B TOGGLE RAISE HAND" class="button">
</form>
<form action="/index.html" method="post">
<input type="hidden" id="toggle_video_key_1" name="toggle_video_key_1" value="alt">
<input type="hidden" id="toggle_video_key_2" name="toggle_video_key_2" value="v">
<input type="submit" value="&#x1F3A5 TOGGLE VIDEO" class="button">
</form>
<form action="/index.html" method="post">
<input type="hidden" id="toggle_mute_key_1" name="toggle_mute_key_1" value="alt">
<input type="hidden" id="toggle_mute_key_2" name="toggle_mute_key_2" value="a">
<input type="submit" value="&#x1F3A4 TOGGLE MICROPHONE" class="button">
</form>
<form action="/index.html" method="post">
<input type="hidden" id="toggle_mute_all_key_1" name="toggle_mute_all_key_1" value="alt">
<input type="hidden" id="toggle_mute_all_key_2" name="toggle_mute_all_key_2" value="m">
<input type="submit" value="&#x1F92B TOGGLE MUTE ALL" class="button">
</form>
<form action="/index.html" method="post">
<input type="hidden" id="toggle_screen_share_key_1" name="toggle_screen_share_key_1" value="alt">
<input type="hidden" id="toggle_screen_share_key_2" name="toggle_screen_share_key_2" value="s">
<input type="submit" value="&#x1F4BB TOGGLE SCREEN SHARE" class="button">
</form>
<form action="/index.html" method="post">
<input type="hidden" id="exit_meeting_key_1" name="exit_meeting_key_1" value="alt">
<input type="hidden" id="exit_meeting_key_2" name="exit_meeting_key_2" value="q">
<input type="submit" value="&#x1F6D1 EXIT MEETING" class="button">
</form>
<form action="/ZoomRemoteDir" method="get">
<input type="submit" value="&#x1F4C2 LIST FILES" class="button">
</form>
</div>
</body>
</html>
"""

favicon = b'AAABAAUAEBAAAAEAIABoBAAAVgAAABgYAAABACAAiAkAAL4EAAAgIAAAAQAgAKgQAABGDgAAMDAAAAEACACoDgAA7h4AADAwAAABAAgAqA4AAJYtAAAoAAAAEAAAACAAAAABACAAAAAAAAAEAAB0EgAAdBIAAAAAAAAAAAAA///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////p6en/bm5u/1hYWP9aWlr/Wlpa/1paWv9aWlr/V1dX/5SUlP/////////////////Nzc3/a2tr/9bW1v//////3t7e/x8fH/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9aWlr////////////u7u7/SkpK/wAAAP+mpqb//////93d3f8vKST/i39y/6SmqP+MjpD/iomI/6Ghn/9JWWf/WFla///////+/v7/i4uL/wICAv8AAAD/pqam///////d3t7/JB8d/5N7Zf/6/fz/b4GW/yIgIP+jk4D/do2e/1dYWv//////tbW1/xEREf8AAAD/AAAA/6ampv//////3t7e/x0dHv8mGQ7/3s66/8DS4f8RHSz/IhsU/yYsMP9aW1z/5ubm/zg4OP8AAAD/AAAA/wAAAP+mpqb//////97e3v8fHx//AAAA/3hhTf/4+PP/aX+W/wAABP8AAAD/UFBQ/2RkZP8BAQH/AAAA/wAAAP8AAAD/pqam///////e3t7/Hx8f/wAAAP8aEAf/yrii/9Ti7v8gL0D/AAAA/0dHR/86Ojr/AAAA/wAAAP8AAAD/AAAA/6ampv//////3d3e/ykmIv85ODb/BQkQ/1tGNP/48ef/gpuv/wAAB/9cW1v/x8fH/xkZGf8AAAD/AAAA/wAAAP+mpqb//////9zd3f86MSb/xryt/1dnfP8uJSP/y7ij/+Xy+v8uP1X/WFdX//7+/v+ZmZn/CQkJ/wAAAP8AAAD/pqam///////d3d3/Lyoj/4yAc/+Ymp//h4eI/5iVkf+nqKj/SFZm/1hZW///////9vb2/2ZmZv8BAQH/AAAA/6ampv//////3t7e/x8fH/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9aWlr////////////u7u7/SkpK/wAAAP+mpqb//////+np6f9ubm7/WFhY/1paWv9aWlr/Wlpa/1paWv9XV1f/lJSU/////////////////83Nzf9ra2v/1tbW/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAGAAAADAAAAABACAAAAAAAAAJAAB0EgAAdBIAAAAAAAAAAAAA/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8DAwP99fX3/gICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP9/f3//jY2N//Hx8f///////////////////////v7+/7S0tP+IiIj/5ubm/////////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/HBwc/+Pj4///////////////////////tbW1/xYWFv8AAAD/ioqK/////////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/HBwc/+Pj4//////////////////p6en/SkpK/wAAAP8AAAD/gICA/////////////////4CAgP8JBAD/cWNT/4GBgv+AgH//g4KC/4SEhP+EhIT/goKD/3h9gv8gMD7/GhoZ/+Pj4/////////////////+AgID/AAAA/wAAAP8AAAD/gICA/////////////////3+AgP8LAQD/vZt5/////f/3/f//obHB/4KCg/+Jh4X/2c68//L8//9DY37/GRgX/+Pj4////////////6qqqv8XFxf/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/TjIa/+/fyf/9////gZ++/wMHE/8AAAD/WDkg/+bm2v9DZID/GRgX/+Pj4///////3Nzc/yMjI/8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/BwIA/51+Xf///vf/4/P7/zlUdP8AAAH/EgoF/2tkWf8hMUD/GhoZ/+Tk5P/19fX/WVlZ/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/AAAA/zkjEP/jzbT//////5291v8HFCf/AAAA/wAAAP8AAAD/HBwc/+Pj4/+oqKj/DAwM/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/AAAA/wQAAP+LaUv///vv/+/7//9LaYv/AAAE/wAAAP8AAAD/Hx8f/5iYmP8YGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/AAAA/wAAAP8mFAf/07ub//////+0zeP/ECM5/wAAAP8AAAD/ICAg/21tbf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/a04z//vx4f/5/v//YoWj/wAECf8AAAD/HR0d/83Nzf9XV1f/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8HAgD/Z1xN/y49UP8AAAL/FgkE/8Kjhf////7/yuHx/xozTv8AAAD/HBwc/+Xl5f/e3t7/IyMj/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////39/gP8TCQD/2LyZ/5S00f8HEB7/AAAA/1Y4Iv/z5tD//f///3qbuv8ABBD/Gxsb/+Pj4///////qqqq/xcXF/8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////39/gP8TCQD/2LmX//X8//+gqLz/goKF/5KJg//p3Mn//////9nu+f8rQGD/GhkZ/+Pj4////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8HAgD/a1xL/4GCgv+Eg4P/hISE/4SEhP+AgYH/gIB//3uAgv8nN0j/Ghoc/+Pj4////////////+jo6P9VVVX/AAAA/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/HBwc/+Pj4//////////////////p6en/SkpK/wAAAP8AAAD/gICA/////////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/HBwc/+Pj4///////////////////////tbW1/xYWFv8AAAD/ioqK/////////////////8DAwP99fX3/gICA/4CAgP+AgID/gICA/4CAgP+AgID/gICA/4CAgP9/f3//jY2N//Hx8f///////////////////////v7+/7S0tP+IiIj/5ubm////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAACAAAABAAAAAAQAgAAAAAAAAEAAAdBIAAHQSAAAAAAAAAAAAAP////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////f39/+vr6//pqam/6ampv+mpqb/pqam/6ampv+mpqb/pqam/6ampv+mpqb/pqam/6ampv+mpqb/pqam/6ampv/g4OD///////////////////////////////////////f39/+urq7/rq6u//f39///////////////////////5+fn/xgYGP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6ampv/////////////////////////////////4+Pj/goKC/wUFBf8EBAT/ioqK///////////////////////n5+f/GBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/pqam/////////////////////////////////6+vr/8GBgb/AAAA/wAAAP9ZWVn//////////////////////+fn5/8YGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+mpqb////////////////////////////k5OT/R0dH/wAAAP8AAAD/AAAA/1lZWf//////////////////////5+fn/xcYGP8HBAH/UUMz/1lZWf9ZWVn/WVlZ/1pZWf9aWlr/Wlpa/1paWv9ZWVn/WllZ/0ZQWf8MFh//AAAA/6ampv///////////////////////////2ZmZv8AAAD/AAAA/wAAAP8AAAD/WVlZ///////////////////////n5+f/FxcY/xMKAf/Xqn/////////////9/v//7fL2/+np6P/p6er/6+rq//r49f//////y+j//yI/Wf8AAAD/pqam//////////////////////+5ubn/HR0d/wAAAP8AAAD/AAAA/wAAAP9ZWVn//////////////////////+fn5/8XGBj/AgAA/3tNLf/579P///////T9//9ii7D/FhUi/xgYF/8cGhn/jXVU//zw2v/L6f//Ij9Z/wAAAP+mpqb/////////////////uLi4/xsbG/8AAAD/AAAA/wAAAP8AAAD/AAAA/1lZWf//////////////////////5+fn/xgYGP8AAAD/IAoA/8Sedv////r//////7PT7v8ZKkv/AAAA/wAAAP8oCgD/1bOJ/8/u//8jQFn/AAAA/6ampv////////////n5+f9QUFD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/WVlZ///////////////////////n5+f/GBgY/wAAAP8AAAD/UzIW//PgwP//////9v///2iUuf8BBxj/AAAA/wEAAP9yVzj/iJah/xYpOv8AAAD/pqam///////6+vr/fX19/wcHB/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9ZWVn//////////////////////+fn5/8YGBj/AAAA/wAAAP8OBQD/t4te///+9P//////1Or4/xpCav8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+mpqb//////9ra2v8VFRX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1lZWf//////////////////////5+fn/xgYGP8AAAD/AAAA/wAAAP9FJBD/6Mys///////6////fabL/wUPJP8AAAD/AAAA/wAAAP8AAAD/AAAA/6mpqf/o6Oj/RkZG/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/WVlZ///////////////////////n5+f/GBgY/wAAAP8AAAD/AAAA/woAAP+edkz///ru///////b9P3/M1GA/wAAA/8AAAD/AAAA/wAAAP8AAAD/mZmZ/09PT/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9ZWVn//////////////////////+fn5/8YGBj/AAAA/wAAAP8AAAD/AAAA/zIWCP/gwJP///////////+Uudv/Bxgw/wAAAP8AAAD/AAAA/wAAAP+Pj4//Hh4e/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1lZWf//////////////////////5+fn/xgYGP8AAAD/AAAA/wAAAP8AAAD/AgAA/3lXMv//7dr//////+v4//9EbJf/AAED/wAAAP8AAAD/AAAA/6Ghof+Dg4P/BwcH/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/WVlZ///////////////////////n5+f/GBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/Iw8A/8yqgP////z//////7HU6v8PLUz/AAAA/wAAAP8AAAD/p6en//7+/v+CgoL/BQUF/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9ZWVn//////////////////////+fn5/8XFxj/DAYA/4tvUP9zjZ3/CA8o/wAAAP8AAAD/aTok//jqy///////9P3//1SCq/8ABA//AAAA/wAAAP+mpqb//////+rq6v8lJSX/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1lZWf//////////////////////5+fn/xcXGP8TCgD/16x6/930/v8oTXr/AAAA/wAAAP8SBgD/v5Jq////+P//////xeb0/xsyYv8AAAD/AAAA/6ampv///////////7m5uf8dHR3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/WVlZ///////////////////////n5+f/FxcY/xIKAP/TqXn//v///6a+2v8qM1T/FhYZ/xcUFv9tSSv/8uPF///////4////bZe9/wEEG/8AAAD/pqam/////////////////7a2tv8ODg7/AAAA/wAAAP8AAAD/AAAA/wAAAP9ZWVn//////////////////////+fn5/8XFxj/EwoA/9Sqef///////P7//+7v9f/p6er/6enq/+3r6P/9+vb////////////M5/7/JD5h/wAAAP+mpqb/////////////////8fHx/0lJSf8AAAD/AAAA/wAAAP8AAAD/AAAA/1lZWf//////////////////////5+fn/xcYGP8GAwD/STsq/1lZWf9ZWVn/WlpZ/1paWv9aWlr/WVpa/1lZWf9ZWVn/WVlZ/0xVWv8RGyv/AAAA/6ampv//////////////////////4uLi/0ZGRv8AAAD/AAAA/wAAAP8AAAD/WVlZ///////////////////////n5+f/GBgY/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/pqam////////////////////////////5OTk/0dHR/8AAAD/AAAA/wAAAP9ZWVn//////////////////////+fn5/8YGBj/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+mpqb/////////////////////////////////r6+v/wYGBv8AAAD/AAAA/1lZWf//////////////////////5+fn/xgYGP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6ampv/////////////////////////////////4+Pj/goKC/wUFBf8EBAT/ioqK///////////////////////39/f/r6+v/6ampv+mpqb/pqam/6ampv+mpqb/pqam/6ampv+mpqb/pqam/6ampv+mpqb/pqam/6ampv+mpqb/4ODg///////////////////////////////////////39/f/rq6u/66urv/39/f///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAwAAAAYAAAAAEACAAAAAAAAAkAAHQSAAB0EgAAAAEAAAABAAD///8AAAAAANuQOgCQ2/8AAAA6AGa2/wBmkNsAtmYAALb//wAAAGYAZgAAAP//tgA6kNsA2///AAA6kAAAZrYA/7ZmAJA6AAD//9sAOgAAAP/bkACQZjoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAABAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAABAQEBAQEBAQAAAAAAAAAAAQEBEAAAAAAAAAAAAAAAAAAAAAUBAQEAAAAAAAAAAAABAQEBAQEBAQAAAAAAAAAAAQEBAgAAAAAAAAAAAAAAAAAAAAUBAQEAAAAAAAAAAAEBAQEBAQEBAQAAAAAAAAAAAQEBCgsAAAAADAEBAQEBFRIAAAUBAQEAAAAAAAAAAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQcAAAAACAkBAQEBAQcAAAUBAQEAAAAAAAABAQEBAQEBAQEBAQAAAAAAAAAAAQEBARMUAAAAAAUBAQEBAQoLAAUBAQEAAAAAAAABAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEREgAAAA0OAQEBAQEQAAUBAQEAAAAAAAEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBEAAAAAADBAEBAQEBAQEBAQEAAAAAAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBERIAAAAADwEBAQEBAQEBAQEAAAAAAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQIAAAAAAwQBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQoLAAAAAAwBAQEBAQEBAQEAAAEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQECAAAAAAgJAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQETFAAAAAAMAQEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBBwAAAAANDgEBAQEBAQEAAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBARAAAAAABQEBAQEBAQEAAAEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBARESAAAAAA8BAQEBAQEAAAABAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEQAAAAAAMEAQEBAQEAAAAAAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAgADBAEBAQEKCwAAAAAPAQEBAQEAAAAAAQEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAgANDgEBAQEBAgAAAAAICQEBAQEAAAAAAAEBAQEBAQEBAQEBAQAAAAAAAAAAAQEBAgAABQEBAQEBCgsAAAAADAEBAQEAAAAAAAABAQEBAQEBAQEBAQAAAAAAAAAAAQEBAgAAAAYEAQEBAQcAAAAACAkBAQEAAAAAAAAAAQEBAQEBAQEBAQAAAAAAAAAAAQEBAgAAAAAAAAAAAAAAAAAAAAUBAQEAAAAAAAAAAQEBAQEBAQEBAQAAAAAAAAAAAQEBAgAAAAAAAAAAAAAAAAAAAAMEAQEAAAAAAAAAAAEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAABAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAQEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAEBAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAABAQEBAQAAAAAAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAADAAAABgAAAAAQAIAAAAAAAACQAAdBIAAHQSAAAAAQAAAAEAAP///wAAAAAA25A6AJDb/wAAADoAZrb/AGaQ2wC2ZgAAtv//AAAAZgBmAAAA//+2ADqQ2wDb//8AADqQAABmtgD/tmYAkDoAAP//2wA6AAAA/9uQAJBmOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAABAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAEBAQEBAQEBAAAAAAAAAAABAQEQAAAAAAAAAAAAAAAAAAAABQEBAQAAAAAAAAAAAAEBAQEBAQEBAAAAAAAAAAABAQECAAAAAAAAAAAAAAAAAAAABQEBAQAAAAAAAAAAAQEBAQEBAQEBAAAAAAAAAAABAQEKCwAAAAAMAQEBAQEVEgAABQEBAQAAAAAAAAABAQEBAQEBAQEBAAAAAAAAAAABAQEBBwAAAAAICQEBAQEBBwAABQEBAQAAAAAAAAEBAQEBAQEBAQEBAAAAAAAAAAABAQEBExQAAAAABQEBAQEBCgsABQEBAQAAAAAAAAEBAQEBAQEBAQEBAAAAAAAAAAABAQEBARESAAAADQ4BAQEBARAABQEBAQAAAAAAAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEQAAAAAAMEAQEBAQEBAQEBAQAAAAABAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEREgAAAAAPAQEBAQEBAQEBAQAAAAABAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAgAAAAADBAEBAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBCgsAAAAADAEBAQEBAQEBAQAAAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQIAAAAACAkBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBARMUAAAAAAwBAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEHAAAAAA0OAQEBAQEBAQABAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBEAAAAAAFAQEBAQEBAQAAAQEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBERIAAAAADwEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBARAAAAAAAwQBAQEBAQAAAAABAQEBAQEBAQEBAQEBAAAAAAAAAAABAQECAAMEAQEBAQoLAAAAAA8BAQEBAQAAAAABAQEBAQEBAQEBAQEBAAAAAAAAAAABAQECAA0OAQEBAQECAAAAAAgJAQEBAQAAAAAAAQEBAQEBAQEBAQEBAAAAAAAAAAABAQECAAAFAQEBAQEKCwAAAAAMAQEBAQAAAAAAAAEBAQEBAQEBAQEBAAAAAAAAAAABAQECAAAABgQBAQEBBwAAAAAICQEBAQAAAAAAAAABAQEBAQEBAQEBAAAAAAAAAAABAQECAAAAAAAAAAAAAAAAAAAABQEBAQAAAAAAAAABAQEBAQEBAQEBAAAAAAAAAAABAQECAAAAAAAAAAAAAAAAAAAAAwQBAQAAAAAAAAAAAQEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAEBAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAABAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAQEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAEBAQEBAAAAAAAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='

if __name__ == '__main__':
    main()
